### ISSUE TITLE
gumble_ffmpeg doesn't exist in github

### ISSUE THREAD

**Issue by kojiujau** [jonas747/mumchmark#2]
`ubuntu@pismo-192-168-1-99:~/mumchmark$ go test main.go 
main.go:10:2: cannot find package "github.com/layeh/gumble/gumble_ffmpeg" in any of:
    /usr/lib/go-1.6/src/github.com/layeh/gumble/gumble_ffmpeg (from $GOROOT)
    /home/ubuntu/src/github.com/layeh/gumble/gumble_ffmpeg (from $GOPATH)`

**Comment by jogramming** [comment]
Wasn't sure anyone has been using this so haven't bothered keeping it up to date, i'll get it working again today though.
